
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat May 30 22:50:25 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 31;
  public static final int LBRACKET = 17;
  public static final int CONST = 7;
  public static final int NUMCONST = 8;
  public static final int LPAREN = 14;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int LESS = 39;
  public static final int FOR = 23;
  public static final int MINUS = 30;
  public static final int RPAREN = 15;
  public static final int GRE = 41;
  public static final int AND = 43;
  public static final int LESSEQUAL = 40;
  public static final int OR = 44;
  public static final int COMMA = 6;
  public static final int CLASS = 13;
  public static final int DIVEQUAL = 49;
  public static final int DIV = 35;
  public static final int PLUS = 29;
  public static final int IF = 20;
  public static final int DOT = 33;
  public static final int ABSTRACT = 12;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 32;
  public static final int RETURN = 25;
  public static final int EQUAL = 37;
  public static final int RBRACKET = 18;
  public static final int ISEQUAL = 38;
  public static final int VOIDD = 16;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int PLUSEQUAL = 46;
  public static final int MOD = 36;
  public static final int BREAK = 21;
  public static final int IDENT = 9;
  public static final int ISNOTEQUAL = 45;
  public static final int LBRACE = 3;
  public static final int ELSE = 22;
  public static final int READ = 28;
  public static final int MINUSEQUAL = 47;
  public static final int CHARCONST = 11;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 10;
  public static final int EXTENDS = 26;
  public static final int PROG = 2;
  public static final int MODEQUAL = 50;
  public static final int GREEQUAL = 42;
  public static final int MULEQUAL = 48;
  public static final int PRINT = 27;
}

